// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPXmiObRYIHJaQBZueHRfvD0vY7-8lp5E',
    appId: '1:910258929518:web:07c46e2f614a93b81f0b7f',
    messagingSenderId: '910258929518',
    projectId: 'buhay-437307',
    authDomain: 'buhay-437307.firebaseapp.com',
    storageBucket: 'buhay-437307.appspot.com',
    measurementId: 'G-JRFF312JP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTraLEmH96w6IaDzSSZpCHj_lzLTNuA_A',
    appId: '1:910258929518:android:b22dcb02380f4acb1f0b7f',
    messagingSenderId: '910258929518',
    projectId: 'buhay-437307',
    storageBucket: 'buhay-437307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgf7cn9G0O7JcujVxUwOTS3urZRjeGKJ4',
    appId: '1:910258929518:ios:d6f3a32dadcb59c21f0b7f',
    messagingSenderId: '910258929518',
    projectId: 'buhay-437307',
    storageBucket: 'buhay-437307.appspot.com',
    iosBundleId: 'com.nesvier.buhay',
  );

}