name: Project Buhay Frontend Lint, Test, and Build

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Build and test Buhay
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.24.5"

      - name: Install FVM via Flutter's built-in Dart
        run: flutter pub global activate fvm

      - name: Add FVM to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      
      # - name: FVM Install Flutter 3.19.6
      #   run: fvm install 3.19.6

      # - name: Flutter Doctor for 3.19.6
      #   run: fvm spawn 3.19.6 doctor --verbose

      # - name: FVM Global 3.19.6
      #   run: fvm global 3.19.6

      - name: FVM Use 3.24.5
        run: fvm install 3.24.5 && fvm use 3.24.5

      - name: Verify Flutter version
        run: fvm flutter --version

      - name: Create a .env file using Github secrets
        run: |
          cat <<EOT >> .env
          # LLMs
          OPENAI_API_KEY_1="${{ secrets.OPENAI_API_KEY_1 }}"
          GOOGLE_GEMINI_API_KEY_1="${{ secrets.GOOGLE_GEMINI_API_KEY_1 }}"
          PERPLEXITY_API_KEY_1="${{ secrets.PERPLEXITY_API_KEY_1 }}"

          # Google Maps
          GOOGLE_MAPS_API_KEY_ANDROID_1="${{ secrets.GOOGLE_MAPS_API_KEY_ANDROID_1 }}"
          GOOGLE_MAPS_API_KEY_WEB_1="${{ secrets.GOOGLE_MAPS_API_KEY_WEB_1 }}"
          GOOGLE_MAPS_API_KEY_IP_1="${{ secrets.GOOGLE_MAPS_API_KEY_IP_1 }}"
          GOOGLE_MAPS_API_KEY_1="${{ secrets.GOOGLE_MAPS_API_KEY_1 }}"

          # Appwrite
          APPWRITE_PROJECT_ID="${{ secrets.APPWRITE_PROJECT_ID }}"
          APPWRITE_ENDPOINT="${{ secrets.APPWRITE_ENDPOINT }}"
          APPWRITE_DEV_DATABASE_ID="${{ secrets.APPWRITE_DEV_DATABASE_ID }}"
          APPWRITE_FLOOD_DATA_COLLECTION_ID="${{ secrets.APPWRITE_FLOOD_DATA_COLLECTION_ID }}"
          APPWRITE_EVACUATION_SITES_COLLECTION_ID="${{ secrets.APPWRITE_EVACUATION_SITES_COLLECTION_ID }}"

          # Mapbox
          MAPBOX_SECRET_ACCESS_TOKEN_1="${{ secrets.MAPBOX_SECRET_ACCESS_TOKEN_1 }}"
          MAPBOX_PUBLIC_ACCESS_TOKEN_1="${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN_1 }}"
          EOT

      - name: Install Flutter dependencies
        run: fvm flutter pub get

      - name: Generate env.g.dart file
        run: fvm dart run build_runner build --delete-conflicting-outputs

      - name: Update local.properties
        run: |
          echo "APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }}" >> android/local.properties
          echo "GOOGLE_MAPS_API_KEY_1=${{ secrets.GOOGLE_MAPS_API_KEY_1 }}" >> android/local.properties
          echo "MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}" >> android/gradle.properties

      - name: Run Flutter tests
        run: fvm flutter test

      - name: Build APK to test
        run: fvm flutter build apk --debug